# Generated by Django 4.2.16 on 2026-05-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cas_number', models.CharField(blank=True, max_length=50)),
                ('synonyms', models.TextField(blank=True, default='[]')),
                ('epa_waste_code', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(choices=[('P', 'P-list (Acutely Hazardous)'), ('U', 'U-list (Toxic)'), ('F', 'F-list (Non-specific source)'), ('K', 'K-list (Specific source)'), ('D_CHAR', 'Characteristic (D-code)'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('is_ignitable', models.BooleanField(default=False)),
                ('is_corrosive', models.BooleanField(default=False)),
                ('is_reactive', models.BooleanField(default=False)),
                ('is_toxic', models.BooleanField(default=False)),
                ('is_acutely_hazardous', models.BooleanField(default=False)),
                ('flash_point_c', models.FloatField(blank=True, null=True)),
                ('ph_value', models.FloatField(blank=True, null=True)),
                ('tclp_threshold_mgl', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Mixture', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_discarded', models.BooleanField(default=True)),
                ('discard_reason', models.CharField(blank=True, max_length=50)),
                ('process_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteDetermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_solid_waste', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
                ('is_listed_hazardous', models.BooleanField(default=False)),
                ('has_ignitability', models.BooleanField(default=False)),
                ('has_corrosivity', models.BooleanField(default=False)),
                ('has_reactivity', models.BooleanField(default=False)),
                ('has_toxicity', models.BooleanField(default=False)),
                ('is_hazardous_waste', models.BooleanField(default=False)),
                ('waste_codes', models.TextField(default='[]')),
                ('reasoning', models.TextField(default='[]')),
                ('recommendations', models.TextField(blank=True)),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='determinations', to='api.mixture')),
            ],
        ),
        migrations.CreateModel(
            name='MixtureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilograms (kg)'), ('L', 'Liters (L)'), ('pct_weight', '% by Weight'), ('pct_volume', '% by Volume'), ('g', 'Grams (g)'), ('mL', 'Milliliters (mL)'), ('lb', 'Pounds (lb)'), ('gal', 'Gallons (gal)')], max_length=20)),
                ('override_flash_point_c', models.FloatField(blank=True, null=True)),
                ('override_ph', models.FloatField(blank=True, null=True)),
                ('override_is_reactive', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chemical')),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.mixture')),
            ],
        ),
    ]
