# Generated by Django 4.2.30 on 2026-05-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixture',
            name='customer_location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mixture',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
