# Generated by Django 4.2.30 on 2026-05-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customers_and_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('epa_id', models.CharField(blank=True, help_text='US EPA ID Number', max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('site_address', models.CharField(blank=True, help_text='Site address if different from mailing', max_length=500)),
                ('site_city', models.CharField(blank=True, max_length=100)),
                ('site_state', models.CharField(blank=True, max_length=50)),
                ('site_zip_code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='EPAManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_tracking_number', models.CharField(blank=True, max_length=30)),
                ('generator_name', models.CharField(blank=True, max_length=300)),
                ('generator_epa_id', models.CharField(blank=True, max_length=20)),
                ('generator_address', models.CharField(blank=True, max_length=500)),
                ('generator_city', models.CharField(blank=True, max_length=100)),
                ('generator_state', models.CharField(blank=True, max_length=50)),
                ('generator_zip', models.CharField(blank=True, max_length=20)),
                ('generator_phone', models.CharField(blank=True, max_length=50)),
                ('generator_site_address', models.CharField(blank=True, max_length=500)),
                ('emergency_response_phone', models.CharField(blank=True, max_length=50)),
                ('transporter1_name', models.CharField(blank=True, max_length=300)),
                ('transporter1_epa_id', models.CharField(blank=True, max_length=20)),
                ('transporter2_name', models.CharField(blank=True, max_length=300)),
                ('transporter2_epa_id', models.CharField(blank=True, max_length=20)),
                ('designated_facility_name', models.CharField(blank=True, max_length=300)),
                ('designated_facility_address', models.CharField(blank=True, max_length=500)),
                ('designated_facility_city', models.CharField(blank=True, max_length=100)),
                ('designated_facility_state', models.CharField(blank=True, max_length=50)),
                ('designated_facility_zip', models.CharField(blank=True, max_length=20)),
                ('designated_facility_epa_id', models.CharField(blank=True, max_length=20)),
                ('designated_facility_phone', models.CharField(blank=True, max_length=50)),
                ('waste_items', models.TextField(default='[]', help_text='JSON array of waste line items')),
                ('special_handling_instructions', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('determination_ids', models.TextField(default='[]', help_text='JSON array of determination IDs')),
                ('generator_certification', models.BooleanField(default=False)),
                ('generator_printed_name', models.CharField(blank=True, max_length=200)),
                ('generator_signature_date', models.DateField(blank=True, null=True)),
                ('international_shipment', models.BooleanField(default=False)),
                ('import_to_us', models.BooleanField(default=False)),
                ('port_of_entry_exit', models.CharField(blank=True, max_length=200)),
                ('date_leaving_us', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('shipped', 'Shipped'), ('received', 'Received')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generator_shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifests', to='api.shipper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
