# Generated by Django 4.2.30 on 2026-05-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wastedetermination_reviewer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('produced', 'Produced'), ('profile', 'Profile'), ('prof_review', 'Prof Review'), ('quote', 'Quote'), ('order', 'Order'), ('signed', 'Signed'), ('ship_accept', 'Ship Accept'), ('picked_up', 'Picked Up'), ('transit', 'Transit'), ('delivered', 'Delivered'), ('disposed', 'Disposed')], max_length=20)),
                ('entered_at', models.DateTimeField(help_text='Date/time the item entered this stage')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date/time the item completed this stage', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Time spent in this stage in seconds', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_stages', to='api.customer')),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_stages', to='api.mixture')),
            ],
            options={
                'verbose_name_plural': 'journeys',
                'ordering': ['mixture', 'entered_at'],
            },
        ),
    ]
