# Generated by Django 6.0.5 on 2026-05-20 03:30

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_epa_generator_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_code', models.CharField(db_index=True, help_text='2-letter state/territory code', max_length=2)),
                ('rule_category', models.CharField(choices=[('identification', 'Identification'), ('storage', 'Storage'), ('manifest', 'Manifest'), ('transport', 'Transport'), ('reporting', 'Reporting'), ('labeling', 'Labeling')], max_length=20)),
                ('rule_id_code', models.CharField(help_text='e.g., AL-001, CA-003', max_length=20, unique=True)),
                ('rule_reference', models.CharField(blank=True, help_text='Regulation citation', max_length=300)),
                ('description', models.TextField()),
                ('condition_expression', models.TextField(default='{}', help_text='JSON conditions for when this rule applies')),
                ('question_template', models.TextField(default='[]', help_text='JSON array of questions to ask if NEEDS_INFO')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('sunset_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['state_code', 'rule_id_code'],
            },
        ),
        migrations.RemoveField(
            model_name='journey',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mixture',
            name='epa_generator_status',
            field=models.CharField(blank=True, choices=[('VSQG', 'VSQG – Very Small Quantity Generator'), ('SQG', 'SQG – Small Quantity Generator'), ('LQG', 'LQG – Large Quantity Generator')], max_length=4),
        ),
        migrations.AddField(
            model_name='mixture',
            name='generation_date',
            field=models.DateField(blank=True, help_text='Date the waste was generated', null=True),
        ),
        migrations.AddField(
            model_name='mixture',
            name='hold_time_days',
            field=models.IntegerField(blank=True, help_text='Total hold time in days from generation to required pickup', null=True),
        ),
        migrations.AddField(
            model_name='mixture',
            name='pickup_by_date',
            field=models.DateField(blank=True, help_text='Date by which waste must be picked up from generator', null=True),
        ),
        migrations.AddField(
            model_name='mixture',
            name='review_status',
            field=models.CharField(blank=True, choices=[('pending_review', 'Pending Initial Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', help_text='Review workflow status', max_length=20),
        ),
        migrations.AddField(
            model_name='mixture',
            name='shipment_size_qty',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (15, '15'), (30, '30'), (55, '55')], null=True),
        ),
        migrations.AddField(
            model_name='mixture',
            name='shipment_size_unit',
            field=models.CharField(blank=True, choices=[('gallons', 'Gallons'), ('cyb', 'CYB'), ('bulk', 'Bulk')], max_length=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=api.models._generate_order_id, max_length=32, unique=True)),
                ('owner_name', models.CharField(blank=True, help_text='Person who created this order', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open Order'), ('in_quote', 'Waiting for Bid'), ('waiting_signature', 'Waiting for Customer Signature'), ('rejected_transport', 'Rejected by Transport'), ('rejected_tldr', 'Rejected by TLDR')], default='open', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.customer')),
                ('potential_shippers', models.ManyToManyField(blank=True, related_name='orders', to='api.shipper')),
                ('profiles', models.ManyToManyField(blank=True, related_name='orders', to='api.mixture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('open', 'Open'), ('in_quote', 'In Quote'), ('waiting_signature', 'Waiting for Customer Signature'), ('rejected_transport', 'Rejected by Transport'), ('rejected_tldr', 'Rejected by TLDR')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_records', to='api.order')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StateValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('state_code', models.CharField(max_length=2)),
                ('overall_result', models.CharField(choices=[('pass', 'Pass'), ('needs_info', 'Needs Info'), ('fail', 'Fail')], max_length=12)),
                ('rule_results', models.TextField(default='[]', help_text='JSON array of {rule_id, result, details}')),
                ('additional_data_collected', models.TextField(default='{}', help_text='JSON object of answers to state questions')),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_validations', to='api.mixture')),
            ],
            options={
                'ordering': ['-validated_at'],
            },
        ),
    ]
