# Generated by Django 4.2.30 on 2026-05-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_incinerator_alter_bid_id_alter_marketplacelisting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixture',
            name='profile_stage',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved')], default='Draft', help_text='Current stage of the profile: Draft, Pending Review, or Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='journey',
            name='stage',
            field=models.CharField(choices=[('produced', 'Produced'), ('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('profile', 'Profile'), ('prof_review', 'Prof Review'), ('quote', 'Quote'), ('order', 'Order'), ('signed', 'Signed'), ('ship_accept', 'Ship Accept'), ('picked_up', 'Picked Up'), ('transit', 'Transit'), ('delivered', 'Delivered'), ('disposed', 'Disposed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mixture',
            name='review_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_review', 'Pending Initial Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Review workflow status', max_length=20),
        ),
    ]
