# Generated by Django 4.2.30 on 2026-05-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mixture_profile_stage_alter_journey_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixture',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Initial Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Review workflow status', max_length=20),
        ),
    ]
