# Generated by Django 4.2.30 on 2026-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_mixture_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixture',
            name='shipment_size_qty',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (15, '15'), (30, '30'), (55, '55'), (85, '85'), (95, '95')], null=True),
        ),
        migrations.AlterField(
            model_name='mixture',
            name='shipment_size_unit',
            field=models.CharField(blank=True, choices=[('gallons', 'Drums'), ('cyb', 'CYB'), ('bulk', 'Bulk')], max_length=10),
        ),
    ]
