# Generated by Django 4.2.30 on 2026-05-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_mixture_shipment_size_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open Order'), ('in_quote', 'Waiting to Quote'), ('waiting_signature', 'Waiting for Customer Signature'), ('rejected_transport', 'Rejected by Transport'), ('rejected_tldr', 'Rejected by TSDF')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderjourney',
            name='stage',
            field=models.CharField(choices=[('open', 'Open'), ('in_quote', 'In Quote'), ('waiting_signature', 'Waiting for Customer Signature'), ('rejected_transport', 'Rejected by Transport'), ('rejected_tldr', 'Rejected by TSDF')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('SDS', 'Safety Data Sheet'), ('A', 'Analytical')], max_length=3)),
                ('short_name', models.CharField(help_text='Short identifier for the document', max_length=200)),
                ('file', models.FileField(upload_to='profile_documents/')),
                ('stored_filename', models.CharField(help_text='Stored filename with profile number prefix', max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.mixture')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
