# Generated by Django 4.2.30 on 2026-05-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sds_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='added_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chemical',
            name='source',
            field=models.CharField(choices=[('epa_import', 'EPA Import'), ('manual', 'Manual (Admin)')], default='epa_import', max_length=20),
        ),
    ]
