# Generated by Django 4.2.30 on 2026-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chemical_source_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetydatasheet',
            name='hazardous_determination',
            field=models.TextField(blank=True, default='', help_text='JSON object with characteristic hazardous waste determination from SDS Section 9/14 analysis'),
        ),
    ]
