# Generated by Django 4.2.30 on 2026-05-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_mixturecomponent_cas_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='hazardous_waste_description',
            field=models.TextField(blank=True),
        ),
    ]
