# Generated by Django 4.2.30 on 2026-05-30 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_chemical_hazardous_waste_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetydatasheet',
            name='profile_document',
            field=models.ForeignKey(blank=True, help_text='Source document this SDS was parsed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_sds', to='api.profiledocument'),
        ),
    ]
