# Generated by Django 6.0.5 on 2026-05-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_change_sds_profile_document_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixturecomponent',
            name='quantity_max',
            field=models.FloatField(blank=True, help_text='Maximum concentration/quantity', null=True),
        ),
        migrations.AddField(
            model_name='mixturecomponent',
            name='quantity_min',
            field=models.FloatField(blank=True, help_text='Minimum concentration/quantity', null=True),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='associated_profiles',
            field=models.ManyToManyField(blank=True, help_text='Additional profiles this document is associated with', related_name='associated_documents', to='api.mixture'),
        ),
        migrations.AlterField(
            model_name='mixturecomponent',
            name='unit',
            field=models.CharField(choices=[('ppm', 'ppm (mg/L)'), ('ppb', 'ppb'), ('pct', '%'), ('kg', 'Kilograms (kg)'), ('L', 'Liters (L)'), ('pct_weight', '% by Weight'), ('pct_volume', '% by Volume'), ('g', 'Grams (g)'), ('mL', 'Milliliters (mL)'), ('lb', 'Pounds (lb)'), ('gal', 'Gallons (gal)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='file_type',
            field=models.CharField(choices=[('SDS', 'Safety Data Sheet'), ('A', 'Analytical'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
