from django.core.management.base import BaseCommand
from api.models import Chemical


class Command(BaseCommand):
    help = 'Seed the database with EPA RCRA hazardous waste chemicals'

    def handle(self, *args, **options):
        self.stdout.write('Seeding chemicals database...')
        created = 0
        updated = 0

        # ── D-list: Toxicity Characteristic chemicals (D004–D043) ─────────────
        d_list = [
            {'name': 'Arsenic', 'cas_number': '7440-38-2', 'epa_waste_code': 'D004',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 5.0,
             'notes': 'Toxicity characteristic – arsenic'},
            {'name': 'Barium', 'cas_number': '7440-39-3', 'epa_waste_code': 'D005',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 100.0,
             'notes': 'Toxicity characteristic – barium'},
            {'name': 'Cadmium', 'cas_number': '7440-43-9', 'epa_waste_code': 'D006',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 1.0,
             'notes': 'Toxicity characteristic – cadmium'},
            {'name': 'Chromium', 'cas_number': '7440-47-3', 'epa_waste_code': 'D007',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 5.0,
             'notes': 'Toxicity characteristic – chromium'},
            {'name': 'Lead', 'cas_number': '7439-92-1', 'epa_waste_code': 'D008',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 5.0,
             'notes': 'Toxicity characteristic – lead'},
            {'name': 'Mercury', 'cas_number': '7439-97-6', 'epa_waste_code': 'D009',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.2,
             'notes': 'Toxicity characteristic – mercury'},
            {'name': 'Selenium', 'cas_number': '7782-49-2', 'epa_waste_code': 'D010',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 1.0,
             'notes': 'Toxicity characteristic – selenium'},
            {'name': 'Silver', 'cas_number': '7440-22-4', 'epa_waste_code': 'D011',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 5.0,
             'notes': 'Toxicity characteristic – silver'},
            {'name': 'Endrin', 'cas_number': '72-20-8', 'epa_waste_code': 'D012',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.02,
             'notes': 'Toxicity characteristic – endrin (pesticide)'},
            {'name': 'Lindane (gamma-BHC)', 'cas_number': '58-89-9', 'epa_waste_code': 'D013',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.4,
             'notes': 'Toxicity characteristic – lindane'},
            {'name': 'Methoxychlor', 'cas_number': '72-43-5', 'epa_waste_code': 'D014',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 10.0,
             'notes': 'Toxicity characteristic – methoxychlor (pesticide)'},
            {'name': 'Toxaphene', 'cas_number': '8001-35-2', 'epa_waste_code': 'D015',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.5,
             'notes': 'Toxicity characteristic – toxaphene (pesticide)'},
            {'name': '2,4-D (2,4-Dichlorophenoxyacetic acid)', 'cas_number': '94-75-7',
             'epa_waste_code': 'D016', 'category': 'D_CHAR', 'is_toxic': True,
             'tclp_threshold_mgl': 10.0, 'notes': 'Toxicity characteristic – 2,4-D herbicide'},
            {'name': '2,4,5-TP (Silvex)', 'cas_number': '93-72-1', 'epa_waste_code': 'D017',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 1.0,
             'notes': 'Toxicity characteristic – silvex herbicide'},
            {'name': 'Benzene', 'cas_number': '71-43-2', 'epa_waste_code': 'D018',
             'category': 'D_CHAR', 'is_toxic': True, 'is_ignitable': True,
             'flash_point_c': -11.0, 'tclp_threshold_mgl': 0.5,
             'notes': 'Toxicity characteristic – benzene; also ignitable (flash point -11°C)'},
            {'name': 'Carbon tetrachloride', 'cas_number': '56-23-5', 'epa_waste_code': 'D019',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.5,
             'notes': 'Toxicity characteristic – carbon tetrachloride'},
            {'name': 'Chlordane', 'cas_number': '57-74-9', 'epa_waste_code': 'D020',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.03,
             'notes': 'Toxicity characteristic – chlordane (pesticide)'},
            {'name': 'Chlorobenzene', 'cas_number': '108-90-7', 'epa_waste_code': 'D021',
             'category': 'D_CHAR', 'is_toxic': True, 'flash_point_c': 29.0,
             'tclp_threshold_mgl': 100.0,
             'notes': 'Toxicity characteristic – chlorobenzene'},
            {'name': 'Chloroform', 'cas_number': '67-66-3', 'epa_waste_code': 'D022',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 6.0,
             'notes': 'Toxicity characteristic – chloroform'},
            {'name': 'o-Cresol', 'cas_number': '95-48-7', 'epa_waste_code': 'D023',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 200.0,
             'notes': 'Toxicity characteristic – o-cresol'},
            {'name': 'm-Cresol', 'cas_number': '108-39-4', 'epa_waste_code': 'D024',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 200.0,
             'notes': 'Toxicity characteristic – m-cresol'},
            {'name': 'p-Cresol', 'cas_number': '106-44-5', 'epa_waste_code': 'D025',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 200.0,
             'notes': 'Toxicity characteristic – p-cresol'},
            {'name': 'Cresol (mixed isomers)', 'cas_number': '', 'epa_waste_code': 'D026',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 200.0,
             'notes': 'Toxicity characteristic – cresol (mixed isomers)'},
            {'name': '1,4-Dichlorobenzene', 'cas_number': '106-46-7', 'epa_waste_code': 'D027',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 7.5,
             'notes': 'Toxicity characteristic – 1,4-dichlorobenzene'},
            {'name': '1,2-Dichloroethane', 'cas_number': '107-06-2', 'epa_waste_code': 'D028',
             'category': 'D_CHAR', 'is_toxic': True, 'flash_point_c': 13.0,
             'tclp_threshold_mgl': 0.5,
             'notes': 'Toxicity characteristic – 1,2-dichloroethane'},
            {'name': '1,1-Dichloroethylene', 'cas_number': '75-35-4', 'epa_waste_code': 'D029',
             'category': 'D_CHAR', 'is_toxic': True, 'flash_point_c': -28.0,
             'tclp_threshold_mgl': 0.7,
             'notes': 'Toxicity characteristic – 1,1-dichloroethylene'},
            {'name': '2,4-Dinitrotoluene', 'cas_number': '121-14-2', 'epa_waste_code': 'D030',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.13,
             'notes': 'Toxicity characteristic – 2,4-dinitrotoluene'},
            {'name': 'Heptachlor (and its epoxide)', 'cas_number': '76-44-8',
             'epa_waste_code': 'D031', 'category': 'D_CHAR', 'is_toxic': True,
             'tclp_threshold_mgl': 0.008, 'notes': 'Toxicity characteristic – heptachlor'},
            {'name': 'Hexachlorobenzene', 'cas_number': '118-74-1', 'epa_waste_code': 'D032',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.13,
             'notes': 'Toxicity characteristic – hexachlorobenzene'},
            {'name': 'Hexachlorobutadiene', 'cas_number': '87-68-3', 'epa_waste_code': 'D033',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.5,
             'notes': 'Toxicity characteristic – hexachlorobutadiene'},
            {'name': 'Hexachloroethane', 'cas_number': '67-72-1', 'epa_waste_code': 'D034',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 3.0,
             'notes': 'Toxicity characteristic – hexachloroethane'},
            {'name': 'Methyl ethyl ketone (2-Butanone)', 'cas_number': '78-93-3',
             'epa_waste_code': 'D035', 'category': 'D_CHAR', 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': -9.0, 'tclp_threshold_mgl': 200.0,
             'notes': 'Toxicity characteristic – MEK; also ignitable'},
            {'name': 'Nitrobenzene', 'cas_number': '98-95-3', 'epa_waste_code': 'D036',
             'category': 'D_CHAR', 'is_toxic': True, 'flash_point_c': 88.0,
             'tclp_threshold_mgl': 2.0,
             'notes': 'Toxicity characteristic – nitrobenzene'},
            {'name': 'Pentachlorophenol', 'cas_number': '87-86-5', 'epa_waste_code': 'D037',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 100.0,
             'notes': 'Toxicity characteristic – pentachlorophenol'},
            {'name': 'Pyridine', 'cas_number': '110-86-1', 'epa_waste_code': 'D038',
             'category': 'D_CHAR', 'is_toxic': True, 'flash_point_c': 17.0,
             'tclp_threshold_mgl': 5.0,
             'notes': 'Toxicity characteristic – pyridine; also ignitable'},
            {'name': 'Tetrachloroethylene (Perchloroethylene)', 'cas_number': '127-18-4',
             'epa_waste_code': 'D039', 'category': 'D_CHAR', 'is_toxic': True,
             'tclp_threshold_mgl': 0.7,
             'notes': 'Toxicity characteristic – tetrachloroethylene (PCE)'},
            {'name': 'Trichloroethylene', 'cas_number': '79-01-6', 'epa_waste_code': 'D040',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 0.5,
             'notes': 'Toxicity characteristic – trichloroethylene (TCE)'},
            {'name': '2,4,5-Trichlorophenol', 'cas_number': '95-95-4', 'epa_waste_code': 'D041',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 400.0,
             'notes': 'Toxicity characteristic – 2,4,5-trichlorophenol'},
            {'name': '2,4,6-Trichlorophenol', 'cas_number': '88-06-2', 'epa_waste_code': 'D042',
             'category': 'D_CHAR', 'is_toxic': True, 'tclp_threshold_mgl': 2.0,
             'notes': 'Toxicity characteristic – 2,4,6-trichlorophenol'},
            {'name': 'Vinyl chloride', 'cas_number': '75-01-4', 'epa_waste_code': 'D043',
             'category': 'D_CHAR', 'is_toxic': True, 'flash_point_c': -78.0,
             'tclp_threshold_mgl': 0.2,
             'notes': 'Toxicity characteristic – vinyl chloride; also ignitable'},
        ]

        # ── P-list: Acutely Hazardous Wastes ──────────────────────────────────
        p_list = [
            {'name': 'Warfarin (>0.3%)', 'cas_number': '81-81-2', 'epa_waste_code': 'P001',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P001 – acutely hazardous anticoagulant rodenticide'},
            {'name': 'Zinc phosphide (>10%)', 'cas_number': '1314-84-7', 'epa_waste_code': 'P122',
             'category': 'P', 'is_acutely_hazardous': True, 'is_reactive': True,
             'notes': 'P122 – zinc phosphide rodenticide'},
            {'name': 'TEPP (Tetraethyl pyrophosphate)', 'cas_number': '107-49-3',
             'epa_waste_code': 'P111', 'category': 'P', 'is_acutely_hazardous': True,
             'is_toxic': True, 'notes': 'P111 – organophosphate insecticide'},
            {'name': 'Methyl parathion', 'cas_number': '298-00-0', 'epa_waste_code': 'P071',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P071 – organophosphate pesticide'},
            {'name': 'Parathion', 'cas_number': '56-38-2', 'epa_waste_code': 'P089',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P089 – organophosphate insecticide'},
            {'name': 'Acrolein', 'cas_number': '107-02-8', 'epa_waste_code': 'P003',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': -26.0,
             'notes': 'P003 – acrolein; reactive, ignitable, acutely toxic'},
            {'name': 'Acrylonitrile', 'cas_number': '107-13-1', 'epa_waste_code': 'P003',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': 0.0,
             'notes': 'P004 – acrylonitrile; ignitable, acutely toxic'},
            {'name': 'Aldicarb', 'cas_number': '116-06-3', 'epa_waste_code': 'P070',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P070 – aldicarb carbamate pesticide'},
            {'name': 'Aldrin', 'cas_number': '309-00-2', 'epa_waste_code': 'P004',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P004 – aldrin chlorinated pesticide'},
            {'name': 'Allyl alcohol', 'cas_number': '107-18-6', 'epa_waste_code': 'P005',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': 22.0,
             'notes': 'P005 – allyl alcohol'},
            {'name': 'Aluminum phosphide', 'cas_number': '20859-73-8', 'epa_waste_code': 'P006',
             'category': 'P', 'is_acutely_hazardous': True, 'is_reactive': True,
             'notes': 'P006 – aluminum phosphide; water-reactive'},
            {'name': 'Arsenic acid', 'cas_number': '7778-39-4', 'epa_waste_code': 'P010',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_corrosive': True,
             'notes': 'P010 – arsenic acid'},
            {'name': 'Arsenic trioxide', 'cas_number': '1327-53-3', 'epa_waste_code': 'P012',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P012 – arsenic trioxide'},
            {'name': 'Barium cyanide', 'cas_number': '542-62-1', 'epa_waste_code': 'P013',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P013 – barium cyanide'},
            {'name': 'Calcium cyanide', 'cas_number': '592-01-8', 'epa_waste_code': 'P021',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P021 – calcium cyanide'},
            {'name': 'Carbon disulfide', 'cas_number': '75-15-0', 'epa_waste_code': 'P022',
             'category': 'P', 'is_acutely_hazardous': True, 'is_ignitable': True,
             'flash_point_c': -30.0,
             'notes': 'P022 – carbon disulfide; extremely flammable'},
            {'name': 'Chlorine', 'cas_number': '7782-50-5', 'epa_waste_code': 'P023',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_reactive': True,
             'notes': 'P023 – chlorine gas; reactive, acutely toxic'},
            {'name': 'Copper cyanide', 'cas_number': '544-92-3', 'epa_waste_code': 'P029',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P029 – copper cyanide'},
            {'name': 'Cyanogen', 'cas_number': '460-19-5', 'epa_waste_code': 'P031',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': -17.8,
             'notes': 'P031 – cyanogen; ignitable, acutely toxic'},
            {'name': 'Cyanogen chloride', 'cas_number': '506-77-4', 'epa_waste_code': 'P033',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P033 – cyanogen chloride; chemical warfare agent precursor'},
            {'name': 'Diazomethane', 'cas_number': '334-88-3', 'epa_waste_code': 'P036',
             'category': 'P', 'is_acutely_hazardous': True, 'is_reactive': True,
             'is_ignitable': True, 'flash_point_c': -45.0,
             'notes': 'P036 – diazomethane; explosive, highly toxic'},
            {'name': 'Dieldrin', 'cas_number': '60-57-1', 'epa_waste_code': 'P037',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P037 – dieldrin organochlorine pesticide'},
            {'name': 'Fluorine', 'cas_number': '7782-41-4', 'epa_waste_code': 'P056',
             'category': 'P', 'is_acutely_hazardous': True, 'is_reactive': True,
             'is_corrosive': True,
             'notes': 'P056 – fluorine gas; extremely reactive'},
            {'name': 'Hydrocyanic acid', 'cas_number': '74-90-8', 'epa_waste_code': 'P063',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': -17.8,
             'notes': 'P063 – hydrogen cyanide; extremely toxic'},
            {'name': 'Hydrogen fluoride (>37%)', 'cas_number': '7664-39-3',
             'epa_waste_code': 'P056', 'category': 'P', 'is_acutely_hazardous': True,
             'is_corrosive': True, 'ph_value': 1.0,
             'notes': 'P056 – hydrofluoric acid; extremely corrosive and toxic'},
            {'name': 'Hydrogen sulfide', 'cas_number': '7783-06-4', 'epa_waste_code': 'P049',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': -82.0,
             'notes': 'P049 – hydrogen sulfide; ignitable, extremely toxic'},
            {'name': 'Mercury fulminate', 'cas_number': '628-86-4', 'epa_waste_code': 'P065',
             'category': 'P', 'is_acutely_hazardous': True, 'is_reactive': True,
             'notes': 'P065 – mercury fulminate; detonation hazard'},
            {'name': 'Methyl hydrazine', 'cas_number': '60-34-4', 'epa_waste_code': 'P068',
             'category': 'P', 'is_acutely_hazardous': True, 'is_ignitable': True,
             'flash_point_c': -8.0, 'is_toxic': True,
             'notes': 'P068 – methyl hydrazine; carcinogen, ignitable'},
            {'name': 'Nickel carbonyl', 'cas_number': '13463-39-3', 'epa_waste_code': 'P073',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': -21.0,
             'notes': 'P073 – nickel carbonyl; extremely toxic, carcinogenic'},
            {'name': 'Osmium tetroxide', 'cas_number': '20816-12-0', 'epa_waste_code': 'P087',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P087 – osmium tetroxide; extremely toxic oxidizer'},
            {'name': 'Potassium cyanide', 'cas_number': '151-50-8', 'epa_waste_code': 'P098',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P098 – potassium cyanide'},
            {'name': 'Sodium azide', 'cas_number': '26628-22-8', 'epa_waste_code': 'P105',
             'category': 'P', 'is_acutely_hazardous': True, 'is_reactive': True,
             'is_toxic': True,
             'notes': 'P105 – sodium azide; explosive, highly toxic'},
            {'name': 'Sodium cyanide', 'cas_number': '143-33-9', 'epa_waste_code': 'P106',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P106 – sodium cyanide'},
            {'name': 'Strychnine', 'cas_number': '57-24-9', 'epa_waste_code': 'P108',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P108 – strychnine and its salts'},
            {'name': 'Thallium(I) sulfate', 'cas_number': '7446-18-6', 'epa_waste_code': 'P115',
             'category': 'P', 'is_acutely_hazardous': True, 'is_toxic': True,
             'notes': 'P115 – thallium sulfate'},
        ]

        # ── U-list: Toxic Wastes ───────────────────────────────────────────────
        u_list = [
            {'name': 'Acetaldehyde', 'cas_number': '75-07-0', 'epa_waste_code': 'U001',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': -38.0,
             'notes': 'U001 – acetaldehyde; ignitable, toxic'},
            {'name': 'Acetone', 'cas_number': '67-64-1', 'epa_waste_code': 'U002',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': -20.0,
             'notes': 'U002 – acetone (F003 solvent); ignitable'},
            {'name': 'Acetonitrile', 'cas_number': '75-05-8', 'epa_waste_code': 'U003',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 2.0,
             'notes': 'U003 – acetonitrile; ignitable, toxic'},
            {'name': 'Acetophenone', 'cas_number': '98-86-2', 'epa_waste_code': 'U004',
             'category': 'U', 'is_toxic': True,
             'notes': 'U004 – acetophenone'},
            {'name': '2-Acetylaminofluorene (2-AAF)', 'cas_number': '53-96-3',
             'epa_waste_code': 'U005', 'category': 'U', 'is_toxic': True,
             'notes': 'U005 – 2-acetylaminofluorene; carcinogen'},
            {'name': 'Acrylamide', 'cas_number': '79-06-1', 'epa_waste_code': 'U007',
             'category': 'U', 'is_toxic': True,
             'notes': 'U007 – acrylamide; neurotoxin, carcinogen'},
            {'name': 'Acrylic acid', 'cas_number': '79-10-7', 'epa_waste_code': 'U008',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 50.0,
             'notes': 'U008 – acrylic acid; corrosive'},
            {'name': 'Acrylonitrile', 'cas_number': '107-13-1', 'epa_waste_code': 'U009',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 0.0,
             'notes': 'U009 – acrylonitrile; carcinogen, ignitable'},
            {'name': 'Aniline', 'cas_number': '62-53-3', 'epa_waste_code': 'U012',
             'category': 'U', 'is_toxic': True, 'flash_point_c': 70.0,
             'notes': 'U012 – aniline; toxic, potential carcinogen'},
            {'name': 'Benzene', 'cas_number': '71-43-2', 'epa_waste_code': 'U019',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': -11.0,
             'notes': 'U019 – benzene; carcinogen, D018 overlap'},
            {'name': 'Benzal chloride', 'cas_number': '98-87-3', 'epa_waste_code': 'U017',
             'category': 'U', 'is_toxic': True,
             'notes': 'U017 – benzal chloride'},
            {'name': 'Carbon tetrachloride', 'cas_number': '56-23-5', 'epa_waste_code': 'U211',
             'category': 'U', 'is_toxic': True,
             'notes': 'U211 – carbon tetrachloride'},
            {'name': 'Chloroform', 'cas_number': '67-66-3', 'epa_waste_code': 'U044',
             'category': 'U', 'is_toxic': True,
             'notes': 'U044 – chloroform; potential carcinogen'},
            {'name': 'Cyclohexanone', 'cas_number': '108-94-1', 'epa_waste_code': 'U057',
             'category': 'U', 'is_toxic': True, 'flash_point_c': 44.0,
             'notes': 'U057 – cyclohexanone (F003 solvent)'},
            {'name': 'Dichloromethane (Methylene chloride)', 'cas_number': '75-09-2',
             'epa_waste_code': 'U080', 'category': 'U', 'is_toxic': True,
             'notes': 'U080 – methylene chloride; carcinogen'},
            {'name': 'Diethyl ether', 'cas_number': '60-29-7', 'epa_waste_code': 'U117',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': -45.0,
             'notes': 'U117 – diethyl ether (ethyl ether); extremely flammable'},
            {'name': 'Dimethylformamide', 'cas_number': '68-12-2', 'epa_waste_code': 'U056',
             'category': 'U', 'is_toxic': True, 'flash_point_c': 57.0,
             'notes': 'U056 – DMF; reproductive toxin'},
            {'name': 'Ethyl acetate', 'cas_number': '141-78-6', 'epa_waste_code': 'U112',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': -4.0,
             'notes': 'U112 – ethyl acetate (F003 solvent); ignitable'},
            {'name': 'Ethylbenzene', 'cas_number': '100-41-4', 'epa_waste_code': 'U239',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 15.0,
             'notes': 'U239 – ethylbenzene (F003 solvent)'},
            {'name': 'Formaldehyde', 'cas_number': '50-00-0', 'epa_waste_code': 'U122',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 64.0,
             'notes': 'U122 – formaldehyde; carcinogen'},
            {'name': 'Methanol', 'cas_number': '67-56-1', 'epa_waste_code': 'U154',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 11.0,
             'notes': 'U154 – methanol (F003 solvent); ignitable, toxic'},
            {'name': 'Methyl isobutyl ketone (MIBK)', 'cas_number': '108-10-1',
             'epa_waste_code': 'U161', 'category': 'U', 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': 14.0,
             'notes': 'U161 – MIBK (F003 solvent); ignitable'},
            {'name': 'Naphthalene', 'cas_number': '91-20-3', 'epa_waste_code': 'U165',
             'category': 'U', 'is_toxic': True, 'flash_point_c': 79.0,
             'notes': 'U165 – naphthalene; possible carcinogen'},
            {'name': 'Nitrobenzene', 'cas_number': '98-95-3', 'epa_waste_code': 'U169',
             'category': 'U', 'is_toxic': True,
             'notes': 'U169 – nitrobenzene; D036 overlap'},
            {'name': 'n-Butyl alcohol (1-Butanol)', 'cas_number': '71-36-3',
             'epa_waste_code': 'U031', 'category': 'U', 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': 29.0,
             'notes': 'U031 – 1-butanol (F003 solvent); ignitable'},
            {'name': 'Phenol', 'cas_number': '108-95-2', 'epa_waste_code': 'U188',
             'category': 'U', 'is_toxic': True, 'flash_point_c': 79.0,
             'notes': 'U188 – phenol; corrosive, toxic'},
            {'name': 'Pyridine', 'cas_number': '110-86-1', 'epa_waste_code': 'U196',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 17.0,
             'notes': 'U196 – pyridine (F005 solvent); D038 overlap'},
            {'name': 'Styrene', 'cas_number': '100-42-5', 'epa_waste_code': 'U239',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 31.0,
             'notes': 'U239 – styrene'},
            {'name': 'Tetrachloroethylene', 'cas_number': '127-18-4', 'epa_waste_code': 'U210',
             'category': 'U', 'is_toxic': True,
             'notes': 'U210 – tetrachloroethylene (PCE); D039 overlap'},
            {'name': 'Toluene', 'cas_number': '108-88-3', 'epa_waste_code': 'U220',
             'category': 'U', 'is_toxic': True, 'is_ignitable': True, 'flash_point_c': 4.0,
             'notes': 'U220 – toluene (F005 solvent); ignitable'},
            {'name': 'Trichloroethylene', 'cas_number': '79-01-6', 'epa_waste_code': 'U228',
             'category': 'U', 'is_toxic': True,
             'notes': 'U228 – trichloroethylene (TCE); D040 overlap, carcinogen'},
            {'name': 'Xylene (mixed isomers)', 'cas_number': '1330-20-7',
             'epa_waste_code': 'U239', 'category': 'U', 'is_toxic': True,
             'is_ignitable': True, 'flash_point_c': 25.0,
             'notes': 'U239 – xylene (F003 solvent); ignitable'},
        ]

        # ── Common chemicals with ignitability / corrosivity / reactivity ─────
        other_chemicals = [
            # Ignitable solvents / fuels
            {'name': 'Ethanol (Ethyl alcohol)', 'cas_number': '64-17-5', 'epa_waste_code': '',
             'category': 'OTHER', 'is_ignitable': True, 'flash_point_c': 13.0,
             'notes': 'Common ignitable solvent; flash point 13°C'},
            {'name': 'Isopropyl alcohol (IPA)', 'cas_number': '67-63-0', 'epa_waste_code': '',
             'category': 'OTHER', 'is_ignitable': True, 'flash_point_c': 12.0,
             'notes': 'Common ignitable solvent; flash point 12°C'},
            {'name': 'Hexane', 'cas_number': '110-54-3', 'epa_waste_code': '',
             'category': 'OTHER', 'is_ignitable': True, 'flash_point_c': -22.0,
             'notes': 'Extremely flammable solvent; flash point -22°C'},
            {'name': 'Heptane', 'cas_number': '142-82-5', 'epa_waste_code': '',
             'category': 'OTHER', 'is_ignitable': True, 'flash_point_c': -4.0,
             'notes': 'Flammable solvent; flash point -4°C'},
            {'name': 'Gasoline', 'cas_number': '86290-81-5', 'epa_waste_code': '',
             'category': 'OTHER', 'is_ignitable': True, 'flash_point_c': -43.0,
             'notes': 'Flammable petroleum product; flash point -43°C'},
            {'name': 'Diesel fuel', 'cas_number': '68334-30-5', 'epa_waste_code': '',
             'category': 'OTHER', 'is_ignitable': True, 'flash_point_c': 52.0,
             'notes': 'Combustible petroleum product; flash point ~52°C'},
            {'name': 'Methyl tert-butyl ether (MTBE)', 'cas_number': '1634-04-4',
             'epa_waste_code': '', 'category': 'OTHER', 'is_ignitable': True,
             'flash_point_c': -28.0,
             'notes': 'Fuel oxygenate; ignitable, groundwater contaminant'},
            {'name': 'Diethyl ether', 'cas_number': '60-29-7', 'epa_waste_code': '',
             'category': 'OTHER', 'is_ignitable': True, 'flash_point_c': -45.0,
             'notes': 'Extremely flammable solvent/anesthetic; flash point -45°C'},
            # Corrosive acids
            {'name': 'Sulfuric acid (concentrated)', 'cas_number': '7664-93-9',
             'epa_waste_code': '', 'category': 'OTHER', 'is_corrosive': True,
             'ph_value': 0.3,
             'notes': 'Strong mineral acid; highly corrosive, pH ~0.3'},
            {'name': 'Hydrochloric acid (concentrated)', 'cas_number': '7647-01-0',
             'epa_waste_code': '', 'category': 'OTHER', 'is_corrosive': True,
             'ph_value': 0.1,
             'notes': 'Strong mineral acid; highly corrosive, pH ~0.1'},
            {'name': 'Nitric acid (concentrated)', 'cas_number': '7697-37-2',
             'epa_waste_code': '', 'category': 'OTHER', 'is_corrosive': True,
             'is_reactive': True, 'ph_value': 1.0,
             'notes': 'Strong oxidizing acid; corrosive and reactive'},
            {'name': 'Phosphoric acid', 'cas_number': '7664-38-2', 'epa_waste_code': '',
             'category': 'OTHER', 'is_corrosive': True, 'ph_value': 1.5,
             'notes': 'Mineral acid; corrosive at high concentrations'},
            {'name': 'Acetic acid (glacial)', 'cas_number': '64-19-7', 'epa_waste_code': '',
             'category': 'OTHER', 'is_corrosive': True, 'is_ignitable': True,
             'flash_point_c': 39.0, 'ph_value': 2.4,
             'notes': 'Weak acid; corrosive and ignitable at high concentrations'},
            {'name': 'Hydrofluoric acid', 'cas_number': '7664-39-3', 'epa_waste_code': '',
             'category': 'OTHER', 'is_corrosive': True, 'is_toxic': True,
             'ph_value': 1.2,
             'notes': 'Highly corrosive and toxic; etches glass'},
            # Corrosive bases
            {'name': 'Sodium hydroxide (caustic soda)', 'cas_number': '1310-73-2',
             'epa_waste_code': '', 'category': 'OTHER', 'is_corrosive': True,
             'ph_value': 14.0,
             'notes': 'Strong base; highly corrosive, pH ~14'},
            {'name': 'Potassium hydroxide', 'cas_number': '1310-58-3', 'epa_waste_code': '',
             'category': 'OTHER', 'is_corrosive': True, 'ph_value': 14.0,
             'notes': 'Strong base; highly corrosive'},
            {'name': 'Ammonium hydroxide (concentrated)', 'cas_number': '1336-21-6',
             'epa_waste_code': '', 'category': 'OTHER', 'is_corrosive': True,
             'ph_value': 13.0,
             'notes': 'Aqueous ammonia; corrosive, toxic vapors'},
            {'name': 'Calcium hydroxide (slaked lime)', 'cas_number': '1305-62-0',
             'epa_waste_code': '', 'category': 'OTHER', 'is_corrosive': True,
             'ph_value': 12.4,
             'notes': 'Slightly soluble base; corrosive at threshold pH'},
            # Reactive chemicals
            {'name': 'Sodium metal', 'cas_number': '7440-23-5', 'epa_waste_code': '',
             'category': 'OTHER', 'is_reactive': True,
             'notes': 'Alkali metal; violently water-reactive, fire hazard'},
            {'name': 'Potassium metal', 'cas_number': '7440-09-7', 'epa_waste_code': '',
             'category': 'OTHER', 'is_reactive': True,
             'notes': 'Alkali metal; violently water-reactive'},
            {'name': 'Lithium aluminum hydride', 'cas_number': '16853-85-3',
             'epa_waste_code': '', 'category': 'OTHER', 'is_reactive': True,
             'notes': 'Reducing agent; water-reactive, fire hazard'},
            {'name': 'Hydrogen peroxide (>52%)', 'cas_number': '7722-84-1',
             'epa_waste_code': '', 'category': 'OTHER', 'is_reactive': True,
             'is_corrosive': True, 'ph_value': 4.5,
             'notes': 'Strong oxidizer; reactive, corrosive at high concentrations'},
            {'name': 'Perchlorates (mixed)', 'cas_number': '14797-73-0', 'epa_waste_code': '',
             'category': 'OTHER', 'is_reactive': True,
             'notes': 'Oxidizing salts; reactive, fire accelerant'},
        ]

        def upsert(data_list):
            nonlocal created, updated
            for item in data_list:
                defaults = {k: v for k, v in item.items() if k != 'name'}
                obj, was_created = Chemical.objects.get_or_create(
                    name=item['name'],
                    defaults=defaults,
                )
                if was_created:
                    created += 1
                else:
                    # Update fields in case data changed
                    for k, v in defaults.items():
                        setattr(obj, k, v)
                    obj.save()
                    updated += 1

        upsert(d_list)
        upsert(p_list)
        upsert(u_list)
        upsert(other_chemicals)

        self.stdout.write(
            self.style.SUCCESS(
                f'Done. Created: {created}, Updated: {updated}. '
                f'Total chemicals: {Chemical.objects.count()}'
            )
        )
